# Generated by Django 5.1.7 on 2025-03-19 12:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_description', models.TextField()),
                ('package_type', models.CharField(choices=[('document', 'Document'), ('parcel', 'Parcel'), ('fragile', 'Fragile'), ('perishable', 'Perishable')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pickup_street', models.CharField(max_length=255)),
                ('pickup_building', models.CharField(blank=True, max_length=255)),
                ('pickup_city', models.CharField(max_length=100)),
                ('pickup_area', models.CharField(max_length=100)),
                ('pickup_landmark', models.CharField(blank=True, max_length=255)),
                ('pickup_location', models.TextField(help_text='Formatted full address')),
                ('delivery_street', models.CharField(max_length=255)),
                ('delivery_building', models.CharField(blank=True, max_length=255)),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_area', models.CharField(max_length=100)),
                ('delivery_landmark', models.CharField(blank=True, max_length=255)),
                ('delivery_location', models.TextField(help_text='Formatted full address')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_phone', models.CharField(max_length=15)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=15)),
                ('delivery_notes', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('CASH', 'Cash on Delivery'), ('CARD', 'Credit/Debit Card')], max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
