# Generated by Django 5.1.7 on 2025-03-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='worker_rating',
            field=models.IntegerField(blank=True, help_text='Rating from 1-5 stars', null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='worker_rating_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
