# Generated by Django 5.1.7 on 2025-03-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_jobposting_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='employment_type',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship')], default='FULL_TIME', max_length=20),
        ),
    ]
