# Generated by Django 5.1.7 on 2025-03-31 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_earnings'),
        ('users', '0003_remove_jobposting_employment_type_and_more'),
    ]

    operations = [
    ]
